# Generated by Django 4.2.7 on 2023-12-10 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('ANDRA PRADESH', 'ANDRA PRADESH'), ('ARUNACHAL PRADESH', 'ARUNACHAL PRADESH'), ('ASSAM', 'ASSAM'), ('BIHAR', 'BIHAR'), ('CHANDIGARH', 'CHANDIGARH'), ('CHHATTISGARH', 'CHHATTISGARH'), ('DADRA & NAGAR HAVELI', 'DADRA & NAGAR HAVELI'), ('DAMAN & DIU', 'DAMAN & DIU'), ('DELHI', 'DELHI'), ('GOA', 'GOA'), ('GUJARAT', 'GUJARAT'), ('HARYANA', 'HARYANA'), ('HIMACHAL PRADESH', 'HIMACHAL PRADESH'), ('JAMMU & KASHMIR', 'JAMMU & KASHMIR'), ('JHARKHAND', 'JHARKHAND'), ('KARNATAKA', 'KARNATAKA'), ('KERALA', 'KERALA'), ('LAKSHADWEEP', 'LAKSHADWEEP'), ('MADHYA PRADESH', 'MADHYA PRADESH'), ('MAHARASHTRA', 'MAHARASHTRA'), ('MANIPUR', 'MANIPUR'), ('MEGHALAYA', 'MEGHALAYA'), ('MIZORAM', 'MIZORAM'), ('NAGALAND', 'NAGALAND'), ('ODISHA', 'ODISHA'), ('PUDUCHERRY', 'PUDUCHERRY'), ('PUNJAB', 'PUNJAB'), ('RAJASTHAN', 'RAJASTHAN'), ('SIKKIM', 'SIKKIM'), ('TAMIL NADU', 'TAMIL NADU'), ('TELANGANA', 'TELANGANA'), ('TRIPURA', 'TRIPURA'), ('UTTAR PRADESH', 'UTTAR PRADESH'), ('UTTARAKHAND', 'UTTARAKHAND'), ('WEST BENGAL', 'WEST BENGAL')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear')], max_length=2)),
                ('product_image', models.ImageField(upload_to='productimg')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('review', models.TextField(blank=True, max_length=500)),
                ('rating', models.FloatField(default=0)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
